# Generated by Django 6.0 on 2025-12-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora final'),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(default='08:00:00', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(),
        ),
    ]
