# Generated by Django 6.0 on 2025-12-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0002_evento_hora_fim_evento_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
