# Generated by Django 6.0 on 2025-12-12 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0003_evento_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacaoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expiracao', models.DateTimeField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
